package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/gin-gonic/gin"
	_ "github.com/sidji-omnichannel/docs" // docs is generated by Swag CLI
	"github.com/sidji-omnichannel/internal/config"
	"github.com/sidji-omnichannel/internal/database"
	"github.com/sidji-omnichannel/internal/handlers"
	"github.com/sidji-omnichannel/internal/middleware"
	"github.com/sidji-omnichannel/internal/models"
	"github.com/sidji-omnichannel/internal/services"
	"github.com/sidji-omnichannel/internal/websocket"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           Omnichannel Chat Platform API
// @version         1.0
// @description     This is the API server for the Omnichannel Chat Platform.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	// Set Gin mode
	if cfg.App.Env == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	// Connect to PostgreSQL
	db, err := database.NewPostgres(&cfg.Database)
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()
	log.Println("✅ Connected to PostgreSQL")

	// Connect to Redis
	redis, err := database.NewRedis(&cfg.Redis)
	if err != nil {
		log.Printf("⚠️  Failed to connect to Redis: %v (continuing without Redis)", err)
	} else {
		defer redis.Close()
		log.Println("✅ Connected to Redis")
	}

	// Initialize WebSocket hub
	hub := websocket.NewHub()
	go hub.Run()
	log.Println("✅ WebSocket hub started")

	// Initialize services
	authService := services.NewAuthService(db, cfg)
	conversationService := services.NewConversationService(db)
	messageService := services.NewMessageService(db)
	channelService := services.NewChannelService(db, cfg)
	channelService.StartTokenRefresher() // Start background token refresher
	teamService := services.NewTeamService(db)
	contactService := services.NewContactService(db)
	cannedService := services.NewCannedResponseService(db)
	labelService := services.NewLabelService(db)
	mediaService := services.NewMediaService(cfg) // Init MediaService
	aiService, err := services.NewAIService(db, cfg) // Init AI Service
	if err != nil {
		log.Printf("⚠️ Failed to init AI service: %v", err)
	}

	// Initialize handlers
	authHandler := handlers.NewAuthHandler(authService)
	conversationHandler := handlers.NewConversationHandler(conversationService, messageService, channelService, contactService, aiService, hub)
	webhookHandler := handlers.NewWebhookHandler(cfg, channelService, contactService, conversationService, messageService, mediaService, aiService, hub) // Inject MediaService & AIService
	wsHandler := handlers.NewWebSocketHandler(hub)
	channelHandler := handlers.NewChannelHandler(channelService)
	teamHandler := handlers.NewTeamHandler(teamService)
	contactHandler := handlers.NewContactHandler(contactService)
	cannedHandler := handlers.NewCannedResponseHandler(cannedService)
	labelHandler := handlers.NewLabelHandler(labelService)
	aiHandler := handlers.NewAIHandler(aiService)

	// Create Gin router
	router := gin.Default()

	// Apply global middleware
	router.Use(middleware.CORS(&cfg.App))

	// Serve static files (uploads)
	router.Static("/uploads", "./uploads")

	// Swagger route
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Health check endpoint
	router.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status":  "healthy",
			"version": "1.0.0",
		})
	})

	// API routes
	api := router.Group("/api")
	{
		// Auth routes (public)
		auth := api.Group("/auth")
		{
			auth.POST("/register", authHandler.Register)
			auth.POST("/login", authHandler.Login)
		}

		// Webhook routes (public but verified)
		webhooks := api.Group("/webhooks")
		{
			webhooks.GET("", webhookHandler.Verify)              // Meta GET verify
			webhooks.POST("", webhookHandler.Handle)             // Meta POST handle
			webhooks.POST("/meta", webhookHandler.Handle)        // Explicit meta path
			webhooks.POST("/twilio", webhookHandler.HandleTwilio) // Twilio webhook
		}

		// Protected routes
		protected := api.Group("")
		protected.Use(middleware.Auth(&cfg.App))
		{
			// Current user
			protected.GET("/auth/me", authHandler.Me)

			// WebSocket
			protected.GET("/ws", wsHandler.Connect)

			// Conversations
			conversations := protected.Group("/conversations")
			{
				conversations.GET("", conversationHandler.List)
				conversations.GET("/:id", conversationHandler.Get)
				conversations.GET("/:id/messages", conversationHandler.GetMessages)
				
				// Block these if over limit
				restricted := conversations.Group("")
				restricted.Use(middleware.Subscription(db))
				{
					restricted.POST("/:id/assign", conversationHandler.Assign)
					restricted.PATCH("/:id/status", conversationHandler.UpdateStatus)
					restricted.POST("/:id/messages", conversationHandler.SendMessage)
					restricted.POST("/:id/suggest", conversationHandler.SuggestAI)
					restricted.DELETE("/:id", conversationHandler.Delete)
				}
			}

			// Channels
			channels := protected.Group("/channels")
			{
				channels.GET("", channelHandler.List)
				channels.GET("/:id", channelHandler.Get)
				channels.POST("", middleware.RequireRole(models.RoleAdmin), channelHandler.Create)
				channels.POST("/instagram/connect", channelHandler.ConnectInstagram)
				channels.POST("/whatsapp/connect", channelHandler.ConnectWhatsApp)
				channels.POST("/facebook/connect", channelHandler.ConnectFacebook)
				channels.POST("/discover/meta", channelHandler.DiscoverMeta)
				channels.DELETE("/:id", middleware.RequireRole(models.RoleAdmin), channelHandler.Delete)
				channels.POST("/:id/activate", middleware.RequireRole(models.RoleAdmin), channelHandler.Activate)
			}

			// Contacts
			contacts := protected.Group("/contacts")
			{
				contacts.GET("", contactHandler.List)
				contacts.GET("/:id", contactHandler.Get)
				contacts.POST("", contactHandler.Create)
				contacts.PATCH("/:id", contactHandler.Update)
				contacts.DELETE("/:id", contactHandler.Delete)
				contacts.GET("/:id/conversations", contactHandler.GetConversations)
			}

			// Team management
			team := protected.Group("/team")
			{
				team.GET("/organization", teamHandler.GetOrganization)
				team.PATCH("/organization", middleware.RequireRole(models.RoleAdmin), teamHandler.UpdateOrganization)
				team.GET("/members", teamHandler.ListMembers)
				team.GET("/members/:id", teamHandler.GetMember)
				team.POST("/members", middleware.RequireRole(models.RoleAdmin), teamHandler.InviteMember)
				team.PATCH("/members/:id", teamHandler.UpdateMember)
				team.PATCH("/members/:id/role", middleware.RequireRole(models.RoleAdmin), teamHandler.UpdateMemberRole)
				team.DELETE("/members/:id", middleware.RequireRole(models.RoleAdmin), teamHandler.RemoveMember)
			}

			// Canned responses
			apiActions := protected.Group("")
			apiActions.Use(middleware.Subscription(db))
			{
				canned := apiActions.Group("/canned-responses")
				{
					canned.POST("", cannedHandler.Create)
					canned.PUT("/:id", cannedHandler.Update)
					canned.DELETE("/:id", cannedHandler.Delete)
				}
				
				labels := apiActions.Group("/labels")
				{
					labels.POST("", labelHandler.Create)
					labels.PUT("/:id", labelHandler.Update)
					labels.DELETE("/:id", labelHandler.Delete)
				}

				ai := apiActions.Group("/channels/:id/ai")
				{
					ai.PUT("", aiHandler.UpdateConfig)
					ai.POST("/knowledge", aiHandler.AddKnowledge)
					ai.PUT("/knowledge/:kid", aiHandler.UpdateKnowledge)
					ai.DELETE("/knowledge/:kid", aiHandler.DeleteKnowledge)
					ai.POST("/test", aiHandler.TestReply)
				}
			}

			// Read-only Extras
			protected.GET("/canned-responses", cannedHandler.List)
			protected.GET("/canned-responses/search", cannedHandler.Search)
			protected.GET("/labels", labelHandler.List)
			protected.GET("/channels/:id/ai", aiHandler.GetConfig)
			protected.GET("/channels/:id/ai/knowledge", aiHandler.ListKnowledge)
		}
	}

	// Start server
	addr := fmt.Sprintf(":%d", cfg.App.Port)
	log.Printf("🚀 Server starting on http://localhost%s", addr)

	go func() {
		if err := router.Run(addr); err != nil {
			log.Fatalf("Failed to start server: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Println("Shutting down server...")
}
